/**
 * THE IMPORTED CATALOGUE — GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Written by `node scripts/import-maxey-listings.mjs` from Maxey's own live
 * inventory feed, which its site fetches client-side:
 *
 *     https://www.maxeycustomhomes.com/api/listings?includeSold=1
 *
 * 98 homes: 49 double, 12 tiny, 37 single.
 *
 * Anything a human decides — what is standing on the lot, what is featured,
 * what is sold — is NOT in here. That lives in `lotState` in
 * `lib/homes.ts`, which is applied over this file, so re-running the import
 * never overwrites it.
 *
 * 4 of them carry a price. The rest are
 * quoted on options, site work and delivery distance, so the site says "call
 * for pricing" rather than printing a zero.
 *
 * `planImage` is a floor-plan DRAWING and is labelled as one wherever it
 * renders. A home with no photograph falls back to it rather than to a grey
 * rectangle, and never shows it as though it were a photograph. See the head
 * of the import script for how the feed's images were sorted.
 */
import type { CatalogueEntry } from "./homes";

export const catalogue: CatalogueEntry[] = [
  {
    slug: "origin-series-maple",
    name: "Origin Series / MAPLE",
    construction: "manufactured",
    series: "Origin Series",
    model: "MAPLE",
    beds: 3,
    baths: 2,
    sqft: 1264,
    sections: "double",
    sizeCategory: "double",
    price: 89995,
    tourUrl: "https://momento360.com/e/uc/5757b5c0ea5a49eba14588f1354be010?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / MAPLE — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-maple.webp",
  },
  {
    slug: "mini-series-buttercup",
    name: "Mini Series / BUTTERCUP",
    construction: "manufactured",
    series: "Mini Series",
    model: "BUTTERCUP",
    beds: 1,
    baths: 1,
    sqft: 408,
    sections: "single",
    sizeCategory: "tiny",
    price: 39999,
    tourUrl: "https://momento360.com/e/uc/1bd2eb6317e54972836948fd275ac368?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Mini Series / BUTTERCUP — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/mini-series-buttercup.webp",
  },
  {
    slug: "origin-series-redwood",
    name: "Origin Series / REDWOOD",
    construction: "manufactured",
    series: "Origin Series",
    model: "REDWOOD",
    beds: 5,
    baths: 3,
    sqft: 2001,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://momento360.com/e/uc/dce83f0dabaa4e998683a1bc3b2383a8?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / REDWOOD — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-redwood.webp",
  },
  {
    slug: "origin-series-sycamore",
    name: "Origin Series / SYCAMORE",
    construction: "manufactured",
    series: "Origin Series",
    model: "SYCAMORE",
    beds: 4,
    baths: 2,
    sqft: 1791,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://momento360.com/e/uc/05301318428e42c49d074dd1824ca101?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / SYCAMORE — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-sycamore.webp",
  },
  {
    slug: "origin-series-cedar",
    name: "Origin Series / CEDAR",
    construction: "manufactured",
    series: "Origin Series",
    model: "CEDAR",
    beds: 3,
    baths: 2,
    sqft: 1475,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://momento360.com/e/uc/55bb041efbb142c19778babbbf6ab749?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / CEDAR — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-cedar.webp",
  },
  {
    slug: "origin-series-spruce",
    name: "Origin Series / SPRUCE",
    construction: "manufactured",
    series: "Origin Series",
    model: "SPRUCE",
    beds: 3,
    baths: 2,
    sqft: 1475,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://momento360.com/e/uc/dda020784ea74aa8a52c5beac25c0be2?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / SPRUCE — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-spruce.webp",
  },
  {
    slug: "origin-series-oak",
    name: "Origin Series / OAK",
    construction: "manufactured",
    series: "Origin Series",
    model: "OAK",
    beds: 4,
    baths: 2,
    sqft: 1475,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://momento360.com/e/uc/9efe096b2c9d4134b2101366e3a04933?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / OAK — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/origin-series-oak.webp",
  },
  {
    slug: "origin-series-birch",
    name: "Origin Series / BIRCH",
    construction: "manufactured",
    series: "Origin Series",
    model: "BIRCH",
    beds: 3,
    baths: 2,
    sqft: 1140,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/6fe7651ff5c44903887d8a269dbaa94c?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / BIRCH — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-aspen",
    name: "Origin Series / ASPEN",
    construction: "manufactured",
    series: "Origin Series",
    model: "ASPEN",
    beds: 3,
    baths: 2,
    sqft: 1140,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/4c840b26dee64f3c909b1d80511ab038?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / ASPEN — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-magnolia",
    name: "Origin Series /  MAGNOLIA",
    construction: "manufactured",
    series: "Origin Series",
    model: "MAGNOLIA",
    beds: 3,
    baths: 2,
    sqft: 1001,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/a79debbac097421bb0a7aeedd2accdbf?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series /  MAGNOLIA — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-cypress",
    name: "Origin Series /  CYPRESS",
    construction: "manufactured",
    series: "Origin Series",
    model: "CYPRESS",
    beds: 4,
    baths: 2,
    sqft: 1001,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/5fc4ebff7c30453cab9da9c451f148fa?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series /  CYPRESS — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-hickory",
    name: "Origin Series / HICKORY",
    construction: "manufactured",
    series: "Origin Series",
    model: "HICKORY",
    beds: 3,
    baths: 2,
    sqft: 869,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/6cce54f95a064b38bcc6f3647cd2b284?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / HICKORY — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-dogwood",
    name: "Origin Series / DOGWOOD",
    construction: "manufactured",
    series: "Origin Series",
    model: "DOGWOOD",
    beds: 2,
    baths: 2,
    sqft: 790,
    sections: "single",
    sizeCategory: "tiny",
    tourUrl: "https://momento360.com/e/uc/e3440f3b0fcf4085824020a7151eb123?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    scenes: [{"kind":"exterior","caption":"Origin Series / DOGWOOD — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "origin-series-elm",
    name: "Origin Series / ELM",
    construction: "manufactured",
    series: "Origin Series",
    model: "ELM",
    beds: 2,
    baths: 1,
    sqft: 737,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://momento360.com/e/uc/20c36e8f81a0484d94d3a152f0a2f2a2?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Origin Series / ELM — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "mini-series-tulip",
    name: "Mini Series / TULIP",
    construction: "manufactured",
    series: "Mini Series",
    model: "TULIP",
    beds: 2,
    baths: 1,
    sqft: 544,
    sections: "single",
    sizeCategory: "tiny",
    price: 49999,
    tourUrl: "https://momento360.com/e/uc/c610d5b7972c4474a34423a5b60fd7de?utm_campaign=embed&utm_source=other&reset-heading=true&size=large",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Mini Series / TULIP — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/mini-series-tulip.webp",
  },
  {
    slug: "prime-series-3276h42p03",
    name: "Prime Series / 3276H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3276H42P03",
    beds: 4,
    baths: 2,
    sqft: 2305,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show/?play=1&m=1XkaEkEvkvg",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3276h42p03.webp",
  },
  {
    slug: "prime-series-3272h52p03",
    name: "Prime Series / 3272H52P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3272H52P03",
    beds: 5,
    baths: 2,
    sqft: 2184,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3272h52p03.webp",
  },
  {
    slug: "prime-series-3266h42p08",
    name: "Prime Series / 3266H42P08",
    construction: "manufactured",
    series: "Prime Series",
    model: "3266H42P08",
    beds: 4,
    baths: 2,
    sqft: 1881,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3266h42p08.webp",
  },
  {
    slug: "prime-series-2876h53p01",
    name: "Prime Series / 2876H53P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "2876H53P01",
    beds: 5,
    baths: 3,
    sqft: 2027,
    sections: "double",
    sizeCategory: "double",
    year: 2027,
    tourUrl: "https://my.matterport.com/show/?m=PMNy86Pmi96",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 2876H53P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-2876h53p01.webp",
  },
  {
    slug: "prime-series-3276h53p03",
    name: "Prime Series / 3276H53P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3276H53P03",
    beds: 5,
    baths: 3,
    sqft: 2305,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3276h53p03.webp",
  },
  {
    slug: "prime-series-3276h63p03",
    name: "Prime Series / 3276H63P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3276H63P03",
    beds: 4,
    baths: 3,
    sqft: 2305,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3276h63p03.webp",
  },
  {
    slug: "prime-series-3272h42p03",
    name: "Prime Series / 3272H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3272H42P03",
    beds: 4,
    baths: 2,
    sqft: 2185,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3272h42p03.webp",
  },
  {
    slug: "prime-series-3266h32p08",
    name: "Prime Series / 3266H32P08",
    construction: "manufactured",
    series: "Prime Series",
    model: "3266H32P08",
    beds: 3,
    baths: 2,
    sqft: 1881,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3266h32p08.webp",
  },
  {
    slug: "prime-series-3260h32p03",
    name: "Prime Series / 3260H32P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3260H32P03",
    beds: 3,
    baths: 2,
    sqft: 1820,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show/?m=Kc5micAJQTn",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 3260H32P03 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3260h32p03.webp",
  },
  {
    slug: "prime-series-3260h42p03",
    name: "Prime Series / 3260H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3260H42P03",
    beds: 4,
    baths: 2,
    sqft: 1820,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3260h42p03.webp",
  },
  {
    slug: "prime-grand-043",
    name: "Prime Grand 043",
    construction: "manufactured",
    series: "Prime Series",
    model: "Grand 043",
    beds: 4,
    baths: 2,
    sqft: 1813,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show?m=mDLEKL5MrLc",
    tagline: "Find modern and affordable manufactured and modular homes from one of today’s most trusted home builders: Champion Homes.",
    scenes: [{"kind":"exterior","caption":"Prime Grand 043 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-series-3260h32p08",
    name: "Prime Series / 3260H32P08",
    construction: "manufactured",
    series: "Prime Series",
    model: "3260H32P08",
    beds: 3,
    baths: 2,
    sqft: 1699,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3260h32p08.webp",
  },
  {
    slug: "prime-series-3256h42p03",
    name: "Prime Series / 3256H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3256H42P03",
    beds: 4,
    baths: 2,
    sqft: 1699,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show?play=1&lang=en-US&m=Fb6A1HWJoUY",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3256h42p03.webp",
  },
  {
    slug: "prime-series-3252h32p03",
    name: "Prime Series / 3252H32P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3252H32P03",
    beds: 3,
    baths: 2,
    sqft: 1577,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show/?m=8iDfABDZmgi",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 3252H32P03 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3252h32p03.webp",
  },
  {
    slug: "prime-series-2856h32p01",
    name: "Prime Series / 2856H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "2856H32P01",
    beds: 3,
    baths: 2,
    sqft: 1493,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show/?m=YYGNMzKZEsa",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 2856H32P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-2856h32p01.webp",
  },
  {
    slug: "prime-series-2856h42p01",
    name: "Prime Series / 2856H42P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "2856H42P01",
    beds: 4,
    baths: 2,
    sqft: 1493,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-2856h42p01.webp",
  },
  {
    slug: "prime-series-3252h32p06",
    name: "Prime Series / 3252H32P06",
    construction: "manufactured",
    series: "Prime Series",
    model: "3252H32P06",
    beds: 3,
    baths: 2,
    sqft: 1456,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-3252h32p06.webp",
  },
  {
    slug: "prime-series-mercer-2852h32p01",
    name: "Prime Series / Mercer 2852H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "Mercer 2852H32P01",
    beds: 3,
    baths: 2,
    sqft: 1387,
    sections: "double",
    sizeCategory: "double",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-mercer-2852h32p01.webp",
  },
  {
    slug: "prime-series-churchill-2848h32p06",
    name: "Prime Series / Churchill 2848H32P06",
    construction: "manufactured",
    series: "Prime Series",
    model: "Churchill 2848H32P06",
    beds: 3,
    baths: 2,
    sqft: 1280,
    sections: "double",
    sizeCategory: "double",
    tourUrl: "https://my.matterport.com/show/?play=1&m=qyjVgYGUVT4",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / Churchill 2848H32P06 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-churchill-2848h32p06.webp",
  },
  {
    slug: "prime-series-1676h32p01",
    name: "Prime Series / 1676H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1676H32P01",
    beds: 3,
    baths: 2,
    sqft: 1153,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=ZTmMr9FdPpr",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 1676H32P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1676h32p01.webp",
  },
  {
    slug: "prime-series-1676h42p01",
    name: "Prime Series / 1676H42P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1676H42P01",
    beds: 3,
    baths: 2,
    sqft: 1153,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1676h42p01.webp",
  },
  {
    slug: "prime-1666h32p01-261",
    name: "Prime 1666H32P01-261",
    construction: "manufactured",
    series: "Prime Series",
    model: "1666H32P01-261",
    beds: 3,
    baths: 2,
    sqft: 1001,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=FUp3n5MePPY",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime 1666H32P01-261 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-1666h32p01-261.webp",
  },
  {
    slug: "prime-series-1676h32p08",
    name: "Prime Series / 1676H32P08",
    construction: "manufactured",
    series: "Prime Series",
    model: "1676H32P08",
    beds: 3,
    baths: 2,
    sqft: 1031,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show?m=h4Ha7yRJUsb",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 1676H32P08 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1676h32p08.webp",
  },
  {
    slug: "prime-series-1476h42p01",
    name: "Prime Series / 1476H42P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1476H42P01",
    beds: 4,
    baths: 2,
    sqft: 1013,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1476h42p01.webp",
  },
  {
    slug: "prime-series-summit-1476h32p01",
    name: "Prime Series / Summit 1476H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "Summit 1476H32P01",
    beds: 3,
    baths: 2,
    sqft: 1013,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-summit-1476h32p01.webp",
  },
  {
    slug: "prime-series-1672h32p01",
    name: "Prime Series / 1672H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1672H32P01",
    beds: 3,
    baths: 2,
    sqft: 1001,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 1672H32P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1672h32p01.webp",
  },
  {
    slug: "prime-series-edmonson-1666h22p01",
    name: "Prime Series / Edmonson 1666H22P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "Edmonson 1666H22P01",
    beds: 2,
    baths: 2,
    sqft: 1056,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-edmonson-1666h22p01.webp",
  },
  {
    slug: "prime-vertex-043",
    name: "Prime Vertex 043",
    construction: "manufactured",
    series: "Prime Series",
    model: "Vertex 043",
    beds: 3,
    baths: 2,
    sqft: 1001,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=x29bKjegwxW",
    tagline: "Find modern and affordable manufactured and modular homes from one of today’s most trusted home builders: Champion Homes.",
    scenes: [{"kind":"exterior","caption":"Prime Vertex 043 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-series-spire-1660h22p01",
    name: "Prime Series / Spire 1660H22P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "Spire 1660H22P01",
    beds: 2,
    baths: 2,
    sqft: 910,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://discover.matterport.com/space/rMDoYW951KR",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-spire-1660h22p01.webp",
  },
  {
    slug: "prime-series-1466h22902",
    name: "Prime Series / 1466H22902",
    construction: "manufactured",
    series: "Prime Series",
    model: "1466H22902",
    beds: 2,
    baths: 2,
    sqft: 880,
    sections: "single",
    sizeCategory: "single",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1466h22902.webp",
  },
  {
    slug: "prime-series-1466h32p01",
    name: "Prime Series / 1466H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1466H32P01",
    beds: 3,
    baths: 2,
    sqft: 880,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show?play=1&lang=en-US&m=7JBeCGAc1EX",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 1466H32P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1466h32p01.webp",
  },
  {
    slug: "prime-series-1656h32p05",
    name: "Prime Series / 1656H32P05",
    construction: "manufactured",
    series: "Prime Series",
    model: "1656H32P05",
    beds: 3,
    baths: 2,
    sqft: 850,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=bKuBDuPgt3c",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / 1656H32P05 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1656h32p05.webp",
  },
  {
    slug: "prime-series-barkley-1656h22p01",
    name: "Prime Series / Barkley 1656H22P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "Barkley 1656H22P01",
    beds: 2,
    baths: 2,
    sqft: 850,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=jReDcyQfkyc",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / Barkley 1656H22P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-barkley-1656h22p01.webp",
  },
  {
    slug: "prime-series-1456h22p02",
    name: "Prime Series / 1456H22P02",
    construction: "manufactured",
    series: "Prime Series",
    model: "1456H22P02",
    beds: 2,
    baths: 2,
    sqft: 747,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1456h22p02.webp",
  },
  {
    slug: "prime-series-monte-1676h32p06",
    name: "Prime Series / Monte 1676H32P06",
    construction: "manufactured",
    series: "Prime Series",
    model: "Monte 1676H32P06",
    beds: 3,
    baths: 2,
    sqft: 0,
    sections: "single",
    sizeCategory: "single",
    tourUrl: "https://my.matterport.com/show/?m=gXm21jnnyWD",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [{"kind":"exterior","caption":"Prime Series / Monte 1676H32P06 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-monte-1676h32p06.webp",
  },
  {
    slug: "prime-series-1636h11p01",
    name: "Prime Series / 1636H11P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1636H11P01",
    beds: 1,
    baths: 1,
    sqft: 576,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "All sizes and dimensions are nominal or based on approximate builder measurements. The builder reserves the right to make changes due to any changes in material, color, specifications, and features anytime without notice or obligation.",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/prime-series-1636h11p01.webp",
  },
  {
    slug: "prime-3256h42p03",
    name: "Prime 3256H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3256H42P03",
    beds: 4,
    baths: 2,
    sqft: 1700,
    sections: "double",
    sizeCategory: "double",
    scenes: [{"kind":"exterior","caption":"Prime 3256H42P03 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-3260h32p03-042",
    name: "Prime 3260H32P03 042",
    construction: "manufactured",
    series: "Prime Series",
    model: "3260H32P03 042",
    beds: 3,
    baths: 2,
    sqft: 1819,
    sections: "double",
    sizeCategory: "double",
    scenes: [{"kind":"exterior","caption":"Prime 3260H32P03 042 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-3276h42p03",
    name: "Prime 3276H42P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3276H42P03",
    beds: 4,
    baths: 2,
    sqft: 1700,
    sections: "double",
    sizeCategory: "double",
    scenes: [{"kind":"exterior","caption":"Prime 3276H42P03 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-3256h32p03",
    name: "Prime 3256H32P03",
    construction: "manufactured",
    series: "Prime Series",
    model: "3256H32P03",
    beds: 3,
    baths: 2,
    sqft: 1699,
    sections: "double",
    sizeCategory: "double",
    scenes: [{"kind":"exterior","caption":"Prime 3256H32P03 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-3252h32p01",
    name: "Prime 3252H32P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "3252H32P01",
    beds: 3,
    baths: 2,
    sqft: 1577,
    sections: "double",
    sizeCategory: "double",
    scenes: [{"kind":"exterior","caption":"Prime 3252H32P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-1676h32p01-042",
    name: "Prime 1676H32P01 042",
    construction: "manufactured",
    series: "Prime Series",
    model: "1676H32P01 042",
    beds: 3,
    baths: 2,
    sqft: 1152,
    sections: "single",
    sizeCategory: "single",
    scenes: [{"kind":"exterior","caption":"Prime 1676H32P01 042 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-1476h42p01",
    name: "Prime 1476H42P01",
    construction: "manufactured",
    series: "Prime Series",
    model: "1476H42P01",
    beds: 4,
    baths: 2,
    sqft: 1013,
    sections: "single",
    sizeCategory: "single",
    scenes: [{"kind":"exterior","caption":"Prime 1476H42P01 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "prime-1466h32p01-042",
    name: "Prime 1466H32P01 042",
    construction: "manufactured",
    series: "Prime Series",
    model: "1466H32P01 042",
    beds: 3,
    baths: 2,
    sqft: 880,
    sections: "single",
    sizeCategory: "single",
    scenes: [{"kind":"exterior","caption":"Prime 1466H32P01 042 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "dutch-elite-1440",
    name: "Dutch Elite 1440",
    construction: "manufactured",
    model: "Dutch Elite 1440",
    beds: 2,
    baths: 1,
    sqft: 533,
    sections: "single",
    sizeCategory: "tiny",
    price: 57999,
    wasPrice: 59999,
    scenes: [{"kind":"exterior","caption":"Dutch Elite 1440 — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
  },
  {
    slug: "the-yukon",
    name: "The Yukon",
    construction: "manufactured",
    model: "The Yukon",
    beds: 4,
    baths: 2,
    sqft: 2280,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 76' Doublewide - 2,280 SF\n4 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-yukon.webp",
  },
  {
    slug: "the-alpha",
    name: "The Alpha",
    construction: "manufactured",
    model: "The Alpha",
    beds: 4,
    baths: 2,
    sqft: 2280,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 76' Doublewide - 2,280 SF\n4 Bed x 2 Bath\n5th Bedroom Option\nBunk Room Option\n3rd Bathroom Option\nPrimary Bathroom Option",
    scenes: [{"kind":"exterior","caption":"The Alpha — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-alpha.webp",
  },
  {
    slug: "the-claremore",
    name: "The Claremore",
    construction: "manufactured",
    model: "The Claremore",
    beds: 4,
    baths: 2,
    sqft: 2077,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 76' Doublewide - 2,077 SF\n4 Bed x 2 Bath\n3rd Bathroom Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-claremore.webp",
  },
  {
    slug: "the-tahlequah",
    name: "The Tahlequah",
    construction: "manufactured",
    model: "The Tahlequah",
    beds: 4,
    baths: 2,
    sqft: 2077,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 76' Doublewide - 2,077 SF\n4 Bed x 2 Bath\n5th Bedroom Option\n3rd Bathroom Option",
    scenes: [{"kind":"exterior","caption":"The Tahlequah — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-tahlequah.webp",
  },
  {
    slug: "the-stillwater",
    name: "The Stillwater",
    construction: "manufactured",
    model: "The Stillwater",
    beds: 4,
    baths: 2,
    sqft: 2040,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 68' Doublewide - 2,040 SF\n4 Bed x 2 Bath\nGlamour Bath Option",
    scenes: [{"kind":"exterior","caption":"The Stillwater — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-stillwater.webp",
  },
  {
    slug: "the-bartlesville",
    name: "The Bartlesville",
    construction: "manufactured",
    model: "The Bartlesville",
    beds: 4,
    baths: 2,
    sqft: 1920,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 64' Doublewide - 1,920 SF\n4 Bed x 2 Bath",
    scenes: [{"kind":"exterior","caption":"The Bartlesville — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-bartlesville.webp",
  },
  {
    slug: "the-ardmore",
    name: "The Ardmore",
    construction: "manufactured",
    model: "The Ardmore",
    beds: 3,
    baths: 2,
    sqft: 1859,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 68' Doublewide - 1,859 SF\n3 Bed x 2 Bath\n4th Bedroom Option\n3rd Bathroom Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-ardmore.webp",
  },
  {
    slug: "the-enid",
    name: "The Enid",
    construction: "manufactured",
    model: "The Enid",
    beds: 4,
    baths: 2,
    sqft: 1749,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 64' Doublewide - 1,749 SF\n4 Bed x 2 Bath\n5th Bedroom Option\nGlamour Bathroom Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-enid.webp",
  },
  {
    slug: "the-red-river",
    name: "The Red River",
    construction: "manufactured",
    model: "The Red River",
    beds: 3,
    baths: 2,
    sqft: 1680,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 56' Doublewide - 1,680 SF\n3 Bed x 2 Bath\nOptional Laundry Sink",
    scenes: [{"kind":"exterior","caption":"The Red River — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-red-river.webp",
  },
  {
    slug: "the-muskogee",
    name: "The Muskogee",
    construction: "manufactured",
    model: "The Muskogee",
    beds: 3,
    baths: 2,
    sqft: 1560,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 52' Doublewide - 1,560 SF\n3 Bed x 2 Bath\nPrimary Bath Option\nTransom Windows Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-muskogee.webp",
  },
  {
    slug: "the-shawnee",
    name: "The Shawnee",
    construction: "manufactured",
    model: "The Shawnee",
    beds: 3,
    baths: 2,
    sqft: 1680,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 56' Doublewide - 1,680 SF\n3 Bed x 2 Bath\nPrimary Bath Option\nTransom Windows Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-shawnee.webp",
  },
  {
    slug: "the-ponca",
    name: "The Ponca",
    construction: "manufactured",
    model: "The Ponca",
    beds: 3,
    baths: 2,
    sqft: 1680,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 56' Doublewide - 1,680 SF\n3 Bed x 2 Bath",
    scenes: [{"kind":"exterior","caption":"The Ponca — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-ponca.webp",
  },
  {
    slug: "the-reno",
    name: "The Reno",
    construction: "manufactured",
    model: "The Reno",
    beds: 3,
    baths: 2,
    sqft: 1680,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 56' Doublewide - 1,680 SF\n3 Bed x 2 Bath\n4th Bedroom Option",
    scenes: [{"kind":"exterior","caption":"The Reno — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-reno.webp",
  },
  {
    slug: "the-woodward",
    name: "The Woodward",
    construction: "manufactured",
    model: "The Woodward",
    beds: 3,
    baths: 2,
    sqft: 1531,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 56' Doublewide - 1,531 SF\n3 Bed x 2 Bath\n4th Bedroom Option",
    scenes: [{"kind":"exterior","caption":"The Woodward — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-woodward.webp",
  },
  {
    slug: "the-duncan",
    name: "The Duncan",
    construction: "manufactured",
    model: "The Duncan",
    beds: 4,
    baths: 2,
    sqft: 1531,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 56' Doublewide - 1,531 SF\n4 Bed x 2 Bath\nFlex Room Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-duncan.webp",
  },
  {
    slug: "the-sapulpa",
    name: "The Sapulpa",
    construction: "manufactured",
    model: "The Sapulpa",
    beds: 3,
    baths: 2,
    sqft: 1531,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 60' Doublewide - 1,531 SF\n3 Bed x 2 Bath\n4th Bedroom Option\n3rd Bathroom Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-sapulpa.webp",
  },
  {
    slug: "the-seminole",
    name: "The Seminole",
    construction: "manufactured",
    model: "The Seminole",
    beds: 3,
    baths: 2,
    sqft: 1440,
    sections: "double",
    sizeCategory: "double",
    tagline: "32' x 48' Doublewide - 1,440 SF\n3 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-seminole.webp",
  },
  {
    slug: "the-pawnee",
    name: "The Pawnee",
    construction: "manufactured",
    model: "The Pawnee",
    beds: 3,
    baths: 2,
    sqft: 1421,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 52' Doublewide - 1,421 SF\n3 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-pawnee.webp",
  },
  {
    slug: "the-okemah",
    name: "The Okemah",
    construction: "manufactured",
    model: "The Okemah",
    beds: 3,
    baths: 2,
    sqft: 1312,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 48' Doublewide - 1,312 SF\n3 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-okemah.webp",
  },
  {
    slug: "the-bristow",
    name: "The Bristow",
    construction: "manufactured",
    model: "The Bristow",
    beds: 3,
    baths: 2,
    sqft: 1203,
    sections: "double",
    sizeCategory: "double",
    tagline: "28' x 44' Doublewide - 1,203 SF\n3 Bed x 2 Bath\nGlamour Bath Option",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-bristow.webp",
  },
  {
    slug: "the-checotah",
    name: "The Checotah",
    construction: "manufactured",
    model: "The Checotah",
    beds: 3,
    baths: 2,
    sqft: 1140,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 76' Singlewide - 1,140 SF\n3 Bed x 2 Bath",
    scenes: [{"kind":"exterior","caption":"The Checotah — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-checotah.webp",
  },
  {
    slug: "the-stroud",
    name: "The Stroud",
    construction: "manufactured",
    model: "The Stroud",
    beds: 3,
    baths: 2,
    sqft: 1156,
    sections: "single",
    sizeCategory: "single",
    tagline: "18' x 76' Singlewide - 1,156 SF\n3 Bed x 2 Bath\n8' Front Porch\nAlternate Kitchen Option",
    scenes: [{"kind":"exterior","caption":"The Stroud — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-stroud.webp",
  },
  {
    slug: "the-vinita",
    name: "The Vinita",
    construction: "manufactured",
    model: "The Vinita",
    beds: 3,
    baths: 2,
    sqft: 1140,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 76' Singlewide - 1,140 SF\n3 Bed x 2 Bath",
    scenes: [{"kind":"exterior","caption":"The Vinita — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-vinita.webp",
  },
  {
    slug: "the-clinton",
    name: "The Clinton",
    construction: "manufactured",
    model: "The Clinton",
    beds: 3,
    baths: 2,
    sqft: 1080,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 72' Singlewide - 1,080 SF\n3 Bed x 2 Bath\nMultiple Kitchen Options",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-clinton.webp",
  },
  {
    slug: "the-cordell",
    name: "The Cordell",
    construction: "manufactured",
    model: "The Cordell",
    beds: 3,
    baths: 2,
    sqft: 1020,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 68' Singlewide - 1,020 SF\n3 Bed x 2 Bath",
    scenes: [{"kind":"exterior","caption":"The Cordell — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-cordell.webp",
  },
  {
    slug: "the-madill",
    name: "The Madill",
    construction: "manufactured",
    model: "The Madill",
    beds: 3,
    baths: 2,
    sqft: 984,
    sections: "single",
    sizeCategory: "single",
    tagline: "14' x 72' Singlewide - 984 SF\n3 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-madill.webp",
  },
  {
    slug: "the-hobart",
    name: "The Hobart",
    construction: "manufactured",
    model: "The Hobart",
    beds: 3,
    baths: 2,
    sqft: 929,
    sections: "single",
    sizeCategory: "single",
    tagline: "14' x 68' Singlewide - 929 SF\n3 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-hobart.webp",
  },
  {
    slug: "the-healdton",
    name: "The Healdton",
    construction: "manufactured",
    model: "The Healdton",
    beds: 2,
    baths: 2,
    sqft: 900,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 60' Singlewide - 900 SF\n2 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-healdton.webp",
  },
  {
    slug: "the-marlow",
    name: "The Marlow",
    construction: "manufactured",
    model: "The Marlow",
    beds: 2,
    baths: 1,
    sqft: 850,
    sections: "single",
    sizeCategory: "single",
    tagline: "18' x 50' Singlewide - 850 SF\n2 Bed x 1 Bath\nOptional Deck",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-marlow.webp",
  },
  {
    slug: "the-hinton",
    name: "The Hinton",
    construction: "manufactured",
    model: "The Hinton",
    beds: 2,
    baths: 2,
    sqft: 840,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 56' Singlewide - 840 SF\n2 Bed x 2 Bath\nMultiple Kitchen Options",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-hinton.webp",
  },
  {
    slug: "the-sayre",
    name: "The Sayre",
    construction: "manufactured",
    model: "The Sayre",
    beds: 2,
    baths: 2,
    sqft: 840,
    sections: "single",
    sizeCategory: "single",
    tagline: "16' x 56' Singlewide - 840 SF\n2 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-sayre.webp",
  },
  {
    slug: "the-altus",
    name: "The Altus",
    construction: "manufactured",
    model: "The Altus",
    beds: 2,
    baths: 2,
    sqft: 820,
    sections: "single",
    sizeCategory: "single",
    tagline: "14' x 60' Singlewide - 820 SF\n2 Bed x 2 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-altus.webp",
  },
  {
    slug: "the-durant",
    name: "The Durant",
    construction: "manufactured",
    model: "The Durant",
    beds: 2,
    baths: 1,
    sqft: 765,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "14' x 56' Singlewide - 765 SF\n2 Bed x 1 Bath",
    scenes: [],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-durant.webp",
  },
  {
    slug: "the-spur",
    name: "The Spur",
    construction: "manufactured",
    model: "The Spur",
    beds: 1,
    baths: 1,
    sqft: 472,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "16' x 40' Singlewide - 472 SF\n1 Bed x 1 Bath\nWraparound Porch",
    scenes: [{"kind":"exterior","caption":"The Spur — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-spur.webp",
  },
  {
    slug: "the-guymon",
    name: "The Guymon",
    construction: "manufactured",
    model: "The Guymon",
    beds: 1,
    baths: 1,
    sqft: 396,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "12' x 33' Park Model/Tiny Home - 396 SF\n1 Bed x 1 Bath",
    scenes: [{"kind":"exterior","caption":"The Guymon — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-guymon.webp",
  },
  {
    slug: "the-hollis",
    name: "The Hollis",
    construction: "manufactured",
    model: "The Hollis",
    beds: 1,
    baths: 1,
    sqft: 396,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "12' x 33' Park Model/Tiny Home - 396 SF\n1 Bed x 1 Bath",
    scenes: [{"kind":"exterior","caption":"The Hollis — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-hollis.webp",
  },
  {
    slug: "the-tishom",
    name: "The Tishom",
    construction: "manufactured",
    model: "The Tishom",
    beds: 1,
    baths: 1,
    sqft: 396,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "12' x 33' Park Model/Tiny Home\n1 Bed x 1 Bath",
    scenes: [{"kind":"exterior","caption":"The Tishom — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-tishom.webp",
  },
  {
    slug: "the-calumet",
    name: "The Calumet",
    construction: "manufactured",
    model: "The Calumet",
    beds: 2,
    baths: 1,
    sqft: 396,
    sections: "single",
    sizeCategory: "tiny",
    tagline: "12' x 33' Park Model/Tiny Home - 396 SF\n2 Bed x 1 Bath",
    scenes: [{"kind":"exterior","caption":"The Calumet — exterior"}],
    sourceUrl: "https://www.maxeycustomhomes.com/api/listings?includeSold=1",
    planImage: "/photos/plans/the-calumet.webp",
  },
];
